### PR TITLE
Fix few bogs

### LINKED ISSUE #144: [FEAT] Saving figures in jupyter hub from bcdi scripts
**Describe the bug**
Figures do not save plt.savefig, probably a backend problem

**To Reproduce**
1. Use phdutils.bcdi.gui.gui.Interface class
2. Run preprocess tab
3. Figures appear in the gui
4. Figures save is blank

**Expected behavior**
Non blank figures

**Screenshots**
image

**Python (please complete the following information):**
 - OS: Linux
 - Python version 3.9

### PR DESCRIPTION
**Pull request by DSimonne**
# Pull Request Template

## Description

Fixes bogs linked to facet analyser, figures in preprocessing, some docstrings and bragg peak computation
I advise to not consider the last commit to understand the changes since doit changed a  lot of things.

Fixes #144  (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How has this been tested?

* OS: Debian testing
* Python version: 3.9

- [x] I have run ``doit`` and all tasks have passed

### CODE REVIEW

**Comment by DSimonne** [comment]
To correct the figures saving in postprocessing, the problem is not so simple since there are modification outside the multislices_plot function (directly in postprocessing_runner)

**Comment by carnisj** [comment]
Hi David. I push few commits:
- use the type Optional[str] for `save_as` instead of Union[bool, str]
- solve mypy and black issues
- solve unittest issue (`flip-reconstruction` was again disabled, I thought this was solved already)

Will you work on the postprocessing_runner as well?

Please update your version of black, this is why it tries to modify a lot of files.

**Comment by DSimonne** [comment]
Hi,
I don't understand the problem with flip_reconstruction, it works locally on my computer but not on slurm :/

**Comment by carnisj** [comment]
> Hi, I don't understand the problem with flip_reconstruction, it works locally on my computer but not on slurm :/

Sure but this is not related to the package `bcdi`, therefore the fix on `flip_reconstruction` should not be merged.

**Comment by DSimonne** [comment]
Indeed ... :/

**Comment by DSimonne** [comment]
So how to do this for post-processing in which the figure is modified outside the function, e.g.

```python
    # bulk support
    fig, _, _ = gu.multislices_plot(
        bulk,
        sum_frames=False,
        title="Orthogonal bulk",
        vmin=0,
        vmax=1,
        is_orthogonal=True,
        reciprocal_space=False,
    )
    fig.text(0.60, 0.45, "Scan " + str(scan), size=20)
    fig.text(
        0.60,
        0.40,
        "Bulk - isosurface=" + str("{:.2f}".format(isosurface_strain)),
        size=20,
    )
    plt.pause(0.1)
    if save:
        plt.savefig(
            setup.detector.savedir + "S" + str(scan) + "_bulk" + comment + ".png"
        )
```

It's only for text elements :/

**Comment by carnisj** [comment]
> So how to do this for post-processing in which the figure is modified outside the function, e.g. ...

can you try to replace `plt.savefig` by `fig.savefig` ?

**Comment by DSimonne** [comment]
Nope that does not work :/

**Pull request closed without merging**
