### PR TITLE
Include the correction of detector angles in Setup

### LINKED ISSUE #209: [FEAT]Merge correct_angles script into preprocessing
We could merge the bcdi_correct_angles.py and bcdi_preprocessing.py scripts, many parameters are shared, for the others, one could imagine a boolean parameter "correct" like the "get_temperature" parameter.

### PR DESCRIPTION
**Pull request by carnisj**
# Pull Request Template

## Description

It is now possible to correct directly the detector angles in bcdi_preprocessing_BCDI.py and strain.py

The user can either provide the position of the Bragg peak (parameter `bragg-peak` in the config files). If the parameter `bragg_peak` is not provided, the script will try to find it from the data, at the condition that the direct beam position is provided as well as `template_imagefile` for strain.py

If some parameters are missing, detector angles are not corrected. The user can still provide already corrected detector angles by using the parameters `outofplane_angle` and `inplane_angle`.

In order to keep naming consistent and explicit, the parameters used to define the detector ROI when loading the data where renamed to `center_roi_x` and `center_roi_y`, because they have nothing to do with the position of the Bragg peak (although in practice one often uses the Bragg peak position for the center of the ROI if possible).

Fixes #209 

The part in #209 about the metadata, as well as changing default folder names, should be acted upon in dedicated issues (otherwise this PR would be too big). Note that a folder name can be provided to `bcdi_utils.show_rocking_curve` for saving the figures. 

## Type of change

- [X] New feature (breaking change which adds functionality)

## How has this been tested?

Scripts run with various datasets (ID01, P10) and different conditions (missing parameter etc...)

## Checklist:

- [X] I have made corresponding changes to the documentation
- [X] I have added corresponding unit tests
- [X] I have run ``doit`` and all tasks have passed

### CODE REVIEW

**Comment by DSimonne** [comment]
Are the parameter `cch1, cch2` and `direct_beam` redundant ?

**Comment by DSimonne** [comment]
The positions of the Bragg peaks are found before masking hot pixels which may be unconvenient

**Comment by DSimonne** [comment]
I am not sure if something changed but I had to flip my mask up and down to get the data working, did you add a flip by default for SIXS data ?

**Comment by DSimonne** [comment]
I am working on sixs data from june 2021, as commented earlier, I had to flip the mask up and down, otherwise it seems to work for the central slice but not for the rocking curve:
finalsum_S3116_align-q-y_norm_300_512_512_1_1_1
central_slice
rocking_curve


```python
Direct beam at (inplane 0 deg, out-of-plane 0 deg)(X, Y): 250, 250
Detector angles before correction: inplane 37.49 deg, outofplane 0.14 deg
Corrected detector angles: inplane 37.35 deg, outofplane 0.32 deg
Max at pixel (Z, Y, X):  147 183 197
Data peak value = 9084.0
```

There is a problem with the integration_roi parameter, I am trying to fix it

**Comment by DSimonne** [comment]
I don't know how to edit your branch so that the changes show in this feed, if you know how, please tell me.
I tried to take checkout on your branch and then edit and commit but the changes only appear in my fork.
You can maybe see them there, it's only a few lines.
Notice that the line in setup.py
`"scipy=1.7.2",`
was crashing the install for me, which is why I deleted the version requirements.
Otherwise it works great !
Now I will edit the GUI

**Comment by DSimonne** [comment]
It would be nice to save the correct_angles output in the h5 file, so that I could load them in the GUI after the script is launched

**Comment by DSimonne** [comment]
There is a lot of metadata that I usually try to extract, but since the script is now launched with the command line and not in a function, I have no access to these.
You mentionned that I could launch the script from the GUI and keep the namespace ? Perhaps by utilizing 
`if __name__ == "gui":`
?

I will try to play with this next week maybe.

**Comment by carnisj** [comment]
> Are the parameter `cch1, cch2` and `direct_beam` redundant ?

partially only. `cch1`, `cch2` and `offset_inplane` are the output of a fit in xrayutilities using a mesh of the direct beam of the detector. 

I think that it is easier to leave these parameters as they are (the user knows what to do when he/she selects xrayutilities). Otherwise we would need to add some correction to the provided `direct_beam` and `dirbeam_detector_angles` to match what xrayutilities needs, and add a detailed documentation (that people most likely would not read or find)

**Comment by carnisj** [comment]
> I am working on sixs data from june 2021, as commented earlier, I had to flip the mask up and down, otherwise it seems to work for the central slice but not for the rocking curve

I didn't change anything (consciously) for SIXS. Is this one of these datasets where you tweaked the setup to mimic a theta-2theta scan? There should not be a need to flip anything, and if you flip your dataset the `integration_roi` setting will not be correct anymore (because the 'integration_roi ' is [y_start, y_stop, x_start, x_stop])

The problem is not in the function showing the rocking curve, but in the setup of the scan

**Comment by carnisj** [comment]
> It would be nice to save the correct_angles output in the h5 file, so that I could load them in the GUI after the script is launched

This was already in bcdi_preprocessing_BCDI.py (lines 863-864), I copied these lines in bcdi_strain.py

**Comment by carnisj** [comment]
> There is a lot of metadata that I usually try to extract, but since the script is now launched with the command line and not in a function, I have no access to these. You mentionned that I could launch the script from the GUI and keep the namespace ? Perhaps by utilizing `if __name__ == "gui":` ?
> 
> I will try to play with this next week maybe.

This should be discussed in a dedicated issue.

**Comment by DSimonne** [comment]
> > It would be nice to save the correct_angles output in the h5 file, so that I could load them in the GUI after the script is launched
> 
> This was already in bcdi_preprocessing_BCDI.py (lines 863-864), I copied these lines in bcdi_strain.py

Indeed ! I did not see that they were corrected sorry.

**Comment by DSimonne** [comment]
> > Are the parameter `cch1, cch2` and `direct_beam` redundant ?
> 
> partially only. `cch1`, `cch2` and `offset_inplane` are the output of a fit in xrayutilities using a mesh of the direct beam on the detector.
> 
> I think that it is easier to leave these parameters as they are (the user knows what to do when he/she selects xrayutilities). Otherwise we would need to add some correction to the provided `direct_beam` and `dirbeam_detector_angles` to match what xrayutilities needs, and add a detailed documentation (that people most likely would not read or find or understand)

OK, I will make the difference clear in the GUI

**Comment by DSimonne** [comment]
I added some more changes in my branch, and edited the GUI that now works =)

**Comment by carnisj** [comment]
> I added some more changes in my branch, and edited the GUI that now works =)

ok for your further changes. In order to incorporate it, can you rebase your branch and make a pull request from your fork/correct_angles to upstream/correct_angles?

**Review by DSimonne — APPROVED** [review]

**Pull request merged**
